In [5]:
import pandas as pd
import numpy as np

In [8]:
# Read in realEstate.csv as a data frame

df = pd.read_csv('Sacramentorealestatetransactions.csv')
df.head()

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
0,3526 HIGH ST,SACRAMENTO,95838,CA,2,1,836,Residential,Wed May 21 00:00:00 EDT 2008,59222,38.631913,-121.434879
1,51 OMAHA CT,SACRAMENTO,95823,CA,3,1,1167,Residential,Wed May 21 00:00:00 EDT 2008,68212,38.478902,-121.431028
2,2796 BRANCH ST,SACRAMENTO,95815,CA,2,1,796,Residential,Wed May 21 00:00:00 EDT 2008,68880,38.618305,-121.443839
3,2805 JANETTE WAY,SACRAMENTO,95815,CA,2,1,852,Residential,Wed May 21 00:00:00 EDT 2008,69307,38.616835,-121.439146
4,6001 MCMAHON DR,SACRAMENTO,95824,CA,2,1,797,Residential,Wed May 21 00:00:00 EDT 2008,81900,38.519470,-121.435768

In [10]:
# The simplest pivot table must have a dataframe and an 
# index . Letâ€™s use the city as our index.

pd.pivot_table(df, index=['city']).head()

,baths,beds,latitude,longitude,price,sq__ft,zip
city,,,,,,,
ANTELOPE,2.212121,3.363636,38.714018,-121.362247,232496.393939,1716.636364,95843.0
AUBURN,2.600000,3.000000,38.912847,-121.082133,405890.800000,898.600000,95603.0
CAMERON PARK,1.666667,2.444444,38.685578,-120.998527,267944.444444,224.000000,95682.0
CARMICHAEL,1.850000,3.050000,38.640161,-121.325816,295684.750000,1553.100000,95608.0
CITRUS HEIGHTS,1.914286,3.228571,38.701383,-121.300204,187114.914286,1308.685714,95618.8

In [11]:
# How about indexing on multiple values. Let's look at the 
# data by city and zip next. 

pd.pivot_table(df, index=['city', 'zip']).head()

,,baths,beds,latitude,longitude,price,sq__ft
city,zip,,,,,,
ANTELOPE,95843,2.212121,3.363636,38.714018,-121.362247,232496.393939,1716.636364
AUBURN,95603,2.600000,3.000000,38.912847,-121.082133,405890.800000,898.600000
CAMERON PARK,95682,1.666667,2.444444,38.685578,-120.998527,267944.444444,224.000000
CARMICHAEL,95608,1.850000,3.050000,38.640161,-121.325816,295684.750000,1553.100000
CITRUS HEIGHTS,95610,2.428571,3.428571,38.699737,-121.263907,226436.285714,1578.142857

In [12]:
# What we really want to take a look at next is price. So, 
# let's explicitly define the 'price' column by 
# using the values field.

pd.pivot_table(df, index=['city', 'zip'], values=['price']).head()

                       price
city           zip
ANTELOPE       95843  232496
AUBURN         95603  405890
CAMERON PARK   95682  267944
CARMICHAEL     95608  295684
CITRUS HEIGHTS 95610  226436

In [32]:
# The 'price' column automatically averages the data.  
# We can do a count or a sum by using aggfunc and np.sum.

prices = pd.pivot_table(df, index=['city', 'zip'], values=['price'], columns=['beds', 'baths'], aggfunc=np.sum)
prices

                           price                                            \
beds                           0         1          2
baths                          0         1          1          2         3
city            zip
ANTELOPE        95843        NaN       NaN        NaN   456250.0       NaN
AUBURN          95603        NaN       NaN        NaN   545000.0       NaN
CAMERON PARK    95682   119000.0       NaN        NaN   620000.0       NaN
CARMICHAEL      95608        NaN       NaN        NaN  1136836.0       NaN
CITRUS HEIGHTS  95610        NaN       NaN        NaN        NaN       NaN
                95621        NaN       NaN   286250.0   164000.0       NaN
COOL            95614        NaN       NaN        NaN        NaN       NaN
DIAMOND SPRINGS 95619        NaN       NaN        NaN        NaN       NaN
EL DORADO       95623        NaN       NaN   205000.0        NaN       NaN
EL DORADO HILLS 95762  1843500.0       NaN        NaN        NaN       NaN
ELK GROVE       95624   985000.0       NaN    71000.0   156000.0       NaN
                95757   605500.0       NaN        NaN        NaN       NaN
                95758   406000.0  198000.0        NaN  1011697.0       NaN
ELVERTA         95626        NaN       NaN        NaN        NaN       NaN
FAIR OAKS       95628        NaN       NaN        NaN   372500.0       NaN
FOLSOM          95630   825000.0       NaN        NaN        NaN       NaN
FORESTHILL      95631   194818.0       NaN        NaN        NaN       NaN
GALT            95632   355000.0       NaN        NaN        NaN       NaN
GARDEN VALLEY   95633        NaN       NaN        NaN        NaN       NaN
GOLD RIVER      95670   300000.0       NaN        NaN   299000.0       NaN
GRANITE BAY     95746        NaN       NaN        NaN        NaN       NaN
GREENWOOD       95635        NaN       NaN        NaN        NaN       NaN
LINCOLN         95648  1773762.0       NaN        NaN  1522000.0       NaN
LOOMIS          95650        NaN       NaN        NaN        NaN       NaN
MATHER          95655        NaN       NaN        NaN        NaN       NaN
MEADOW VISTA    95722        NaN       NaN        NaN        NaN       NaN
NORTH HIGHLANDS 95660        NaN       NaN    63000.0   131750.0       NaN
ORANGEVALE      95662        NaN       NaN   334150.0        NaN       NaN
PENRYN          95663        NaN       NaN        NaN        NaN       NaN
PLACERVILLE     95667   270000.0       NaN   211500.0        NaN       NaN
...                          ...       ...        ...        ...       ...
SACRAMENTO      95814        NaN       NaN        NaN        NaN  427500.0
                95815        NaN  106852.0   768300.0        NaN       NaN
                95816   360000.0       NaN   820000.0        NaN       NaN
                95817        NaN       NaN   347050.0        NaN       NaN
                95818        NaN       NaN  1389524.0   205000.0       NaN
                95819        NaN       NaN        NaN        NaN       NaN
                95820        NaN       NaN  1415745.0   123675.0       NaN
                95821        NaN       NaN        NaN        NaN       NaN
                95822        NaN       NaN   212250.0    66500.0       NaN
                95823        NaN       NaN   308172.0   294556.0       NaN
                95824        NaN       NaN   458405.0    93600.0       NaN
                95825   225000.0  305666.0   281000.0   300000.0       NaN
                95826        NaN  160000.0   216960.0        NaN       NaN
                95827        NaN       NaN        NaN        NaN       NaN
                95828        NaN       NaN        NaN   145000.0       NaN
                95829        NaN       NaN        NaN        NaN       NaN
                95831   370000.0       NaN   220000.0   406250.0       NaN
                95832        NaN       NaN        NaN        NaN       NaN
                95833   799500.0       NaN   212000.0        NaN       NaN
                95834  1380500.0       NaN        NaN   352500.0       NaN
                95835   832500.0  325944.0        NaN   373000.0       NaN
                95838   344755.0       NaN   464222.0    91000.0       NaN
                95841        NaN       NaN   307522.0        NaN       NaN
                95842        NaN       NaN   590474.0   334250.0       NaN
                95864        NaN       NaN   203000.0        NaN       NaN
SHINGLE SPRINGS 95682   275000.0       NaN        NaN        NaN       NaN
SLOUGHHOUSE     95683        NaN       NaN        NaN        NaN       NaN
WALNUT GROVE    95690        NaN       NaN        NaN        NaN       NaN
WEST SACRAMENTO 95691   365100.0       NaN   147000.0        NaN       NaN
WILTON          95693   560000.0       NaN        NaN        NaN       NaN

                                                                         \
beds                           3                                      4
baths                          1          2         3       4         1
city            zip
ANTELOPE        95843   223139.0  3516436.0       NaN     NaN       NaN
AUBURN          95603        NaN        NaN  504000.0     NaN       NaN
CAMERON PARK    95682   201000.0  1048500.0       NaN     NaN       NaN
CARMICHAEL      95608   848872.0  1983622.0       NaN     NaN       NaN
CITRUS HEIGHTS  95610        NaN  1134000.0       NaN     NaN       NaN
                95621   746000.0  1974046.0       NaN     NaN       NaN
COOL            95614        NaN   300000.0       NaN     NaN       NaN
DIAMOND SPRINGS 95619        NaN   216033.0       NaN     NaN       NaN
EL DORADO       95623        NaN   289000.0       NaN     NaN       NaN
EL DORADO HILLS 95762        NaN  2263938.0       NaN     NaN       NaN
ELK GROVE       95624        NaN  1674796.0       NaN     NaN       NaN
                95757        NaN  3789142.0  666750.0     NaN       NaN
                95758        NaN  3096271.0  484500.0     NaN       NaN
ELVERTA         95626        NaN   404750.0       NaN     NaN       NaN
FAIR OAKS       95628   574000.0  1105006.0       NaN     NaN       NaN
FOLSOM          95630        NaN  1920323.0       NaN     NaN       NaN
FORESTHILL      95631        NaN        NaN       NaN     NaN       NaN
GALT            95632   295457.0  1664227.0       NaN     NaN       NaN
GARDEN VALLEY   95633        NaN   490000.0       NaN     NaN       NaN
GOLD RIVER      95670        NaN   305000.0       NaN     NaN       NaN
GRANITE BAY     95746        NaN        NaN       NaN     NaN       NaN
GREENWOOD       95635        NaN   395000.0       NaN     NaN       NaN
LINCOLN         95648        NaN   945321.0    1551.0     NaN       NaN
LOOMIS          95650        NaN        NaN       NaN     NaN       NaN
MATHER          95655        NaN   237800.0       NaN     NaN       NaN
MEADOW VISTA    95722   230000.0        NaN       NaN     NaN       NaN
NORTH HIGHLANDS 95660  1125070.0  1098526.0       NaN     NaN       NaN
ORANGEVALE      95662   225000.0  1036250.0       NaN     NaN       NaN
PENRYN          95663        NaN   506688.0       NaN     NaN       NaN
PLACERVILLE     95667        NaN  1951048.0       NaN     NaN       NaN
...                          ...        ...       ...     ...       ...
SACRAMENTO      95814        NaN        NaN  675686.0     NaN       NaN
                95815   273225.0   135500.0       NaN     NaN       NaN
                95816        NaN        NaN       NaN     NaN       NaN
                95817   513750.0   127059.0       NaN     NaN       NaN
                95818   388000.0        NaN       NaN     NaN       NaN
                95819   764000.0   400000.0       NaN     NaN       NaN
                95820  1144297.0   228327.0       NaN     NaN       NaN
                95821   672000.0   250000.0       NaN     NaN       NaN
                95822  1262635.0  1536586.0       NaN     NaN       NaN
                95823   184212.0  5610843.0  347029.0     NaN  166357.0
                95824   691606.0   130000.0       NaN     NaN       NaN
                95825   398012.0   290000.0       NaN     NaN       NaN
                95826   558750.0   885304.0       NaN     NaN       NaN
                95827        NaN   572000.0       NaN     NaN       NaN
                95828   845393.0  3898905.0       NaN     NaN       NaN
                95829        NaN   687012.0       NaN     NaN       NaN
                95831        NaN   583000.0  415000.0     NaN       NaN
                95832   116100.0  1203275.0       NaN     NaN       NaN
                95833   140000.0  1097245.0       NaN     NaN  164000.0
                95834        NaN  1533300.0       NaN     NaN       NaN
                95835        NaN  2939583.0  334000.0     NaN       NaN
                95838   593000.0  2583165.0       NaN     NaN       NaN
                95841   549921.0   178000.0       NaN     NaN       NaN
                95842   198000.0   829895.0       NaN     NaN       NaN
                95864   644000.0   315000.0  660000.0     NaN       NaN
SHINGLE SPRINGS 95682        NaN        NaN       NaN     NaN       NaN
SLOUGHHOUSE     95683        NaN        NaN       NaN  2000.0       NaN
WALNUT GROVE    95690   380000.0        NaN       NaN     NaN       NaN
WEST SACRAMENTO 95691        NaN        NaN       NaN     NaN       NaN
WILTON          95693        NaN   372000.0       NaN     NaN       NaN

                         ...                                               \
beds                     ...                                 5
baths                    ...             3         4         2          3
city            zip      ...
ANTELOPE        95843    ...     1384331.0       NaN       NaN   960000.0
AUBURN          95603    ...      980454.0       NaN       NaN        NaN
CAMERON PARK    95682    ...           NaN       NaN       NaN        NaN
CARMICHAEL      95608    ...      668365.0       NaN       NaN        NaN
CITRUS HEIGHTS  95610    ...      195000.0       NaN       NaN        NaN
                95621    ...      189836.0       NaN       NaN        NaN
COOL            95614    ...           NaN       NaN       NaN        NaN
DIAMOND SPRINGS 95619    ...           NaN       NaN       NaN        NaN
EL DORADO       95623    ...           NaN       NaN       NaN        NaN
EL DORADO HILLS 95762    ...     3509238.0       NaN       NaN   926200.0
ELK GROVE       95624    ...     1704186.0       NaN  222750.0   468976.0
                95757    ...     2856003.0  450000.0       NaN  2219000.0
                95758    ...      470000.0       NaN       NaN   875000.0
ELVERTA         95626    ...           NaN       NaN       NaN        NaN
FAIR OAKS       95628    ...           NaN       NaN       NaN        NaN
FOLSOM          95630    ...     2080000.0       NaN       NaN   901000.0
FORESTHILL      95631    ...           NaN       NaN       NaN        NaN
GALT            95632    ...      578000.0       NaN       NaN        NaN
GARDEN VALLEY   95633    ...           NaN       NaN       NaN        NaN
GOLD RIVER      95670    ...           NaN       NaN       NaN        NaN
GRANITE BAY     95746    ...      600000.0       NaN       NaN  1436200.0
GREENWOOD       95635    ...           NaN       NaN       NaN        NaN
LINCOLN         95648    ...      436746.0  297500.0       NaN   931000.0
LOOMIS          95650    ...           NaN  839000.0       NaN        NaN
MATHER          95655    ...           NaN       NaN       NaN        NaN
MEADOW VISTA    95722    ...           NaN       NaN       NaN        NaN
NORTH HIGHLANDS 95660    ...           NaN       NaN       NaN        NaN
ORANGEVALE      95662    ...           NaN  475000.0       NaN        NaN
PENRYN          95663    ...           NaN       NaN       NaN        NaN
PLACERVILLE     95667    ...      835000.0       NaN       NaN        NaN
...                      ...           ...       ...       ...        ...
SACRAMENTO      95814    ...           NaN       NaN       NaN        NaN
                95815    ...           NaN       NaN       NaN        NaN
                95816    ...      215000.0       NaN       NaN        NaN
                95817    ...           NaN       NaN       NaN        NaN
                95818    ...           NaN       NaN       NaN        NaN
                95819    ...           NaN       NaN  699000.0        NaN
                95820    ...           NaN       NaN  150000.0        NaN
                95821    ...           NaN       NaN       NaN        NaN
                95822    ...           NaN       NaN       NaN        NaN
                95823    ...      738887.0       NaN       NaN        NaN
                95824    ...           NaN       NaN       NaN        NaN
                95825    ...           NaN       NaN       NaN        NaN
                95826    ...      328360.0       NaN       NaN        NaN
                95827    ...           NaN  297000.0       NaN   315537.0
                95828    ...      688000.0  315000.0       NaN        NaN
                95829    ...      971610.0       NaN       NaN   572500.0
                95831    ...           NaN       NaN       NaN   445000.0
                95832    ...      280987.0       NaN       NaN   295000.0
                95833    ...      246000.0       NaN       NaN        NaN
                95834    ...      654000.0       NaN       NaN   924500.0
                95835    ...      808980.0  465000.0       NaN  1712087.0
                95838    ...      137721.0       NaN       NaN        NaN
                95841    ...           NaN       NaN       NaN        NaN
                95842    ...      205000.0       NaN  168000.0        NaN
                95864    ...           NaN       NaN       NaN        NaN
SHINGLE SPRINGS 95682    ...           NaN       NaN       NaN        NaN
SLOUGHHOUSE     95683    ...           NaN       NaN       NaN        NaN
WALNUT GROVE    95690    ...           NaN       NaN       NaN        NaN
WEST SACRAMENTO 95691    ...           NaN       NaN       NaN        NaN
WILTON          95693    ...      884790.0       NaN  579093.0   691659.0

                                                                         \
beds                                              6
baths                         4         5         3         4         5
city            zip
ANTELOPE        95843       NaN       NaN       NaN       NaN       NaN
AUBURN          95603       NaN       NaN       NaN       NaN       NaN
CAMERON PARK    95682       NaN       NaN       NaN       NaN       NaN
CARMICHAEL      95608       NaN       NaN       NaN       NaN       NaN
CITRUS HEIGHTS  95610  256054.0       NaN       NaN       NaN       NaN
                95621       NaN       NaN       NaN       NaN       NaN
COOL            95614       NaN       NaN       NaN       NaN       NaN
DIAMOND SPRINGS 95619       NaN       NaN       NaN       NaN       NaN
EL DORADO       95623       NaN       NaN       NaN       NaN       NaN
EL DORADO HILLS 95762  508000.0       NaN       NaN       NaN  830000.0
ELK GROVE       95624       NaN       NaN  300000.0       NaN       NaN
                95757  895000.0       NaN       NaN       NaN       NaN
                95758       NaN       NaN       NaN       NaN       NaN
ELVERTA         95626       NaN       NaN       NaN       NaN       NaN
FAIR OAKS       95628       NaN  680000.0       NaN       NaN       NaN
FOLSOM          95630       NaN       NaN       NaN       NaN       NaN
FORESTHILL      95631       NaN       NaN       NaN       NaN       NaN
GALT            95632  420000.0       NaN       NaN       NaN       NaN
GARDEN VALLEY   95633       NaN       NaN       NaN       NaN       NaN
GOLD RIVER      95670       NaN       NaN       NaN       NaN       NaN
GRANITE BAY     95746       NaN       NaN       NaN       NaN       NaN
GREENWOOD       95635       NaN       NaN       NaN       NaN       NaN
LINCOLN         95648       NaN       NaN       NaN       NaN       NaN
LOOMIS          95650       NaN       NaN       NaN       NaN       NaN
MATHER          95655       NaN       NaN       NaN       NaN       NaN
MEADOW VISTA    95722       NaN       NaN       NaN       NaN       NaN
NORTH HIGHLANDS 95660       NaN       NaN       NaN       NaN       NaN
ORANGEVALE      95662       NaN       NaN       NaN       NaN       NaN
PENRYN          95663       NaN       NaN       NaN       NaN       NaN
PLACERVILLE     95667       NaN       NaN       NaN       NaN       NaN
...                         ...       ...       ...       ...       ...
SACRAMENTO      95814       NaN       NaN       NaN       NaN       NaN
                95815       NaN       NaN       NaN       NaN       NaN
                95816       NaN       NaN       NaN       NaN       NaN
                95817       NaN       NaN       NaN       NaN       NaN
                95818       NaN       NaN       NaN       NaN       NaN
                95819       NaN       NaN       NaN       NaN       NaN
                95820       NaN       NaN       NaN       NaN       NaN
                95821       NaN       NaN       NaN       NaN       NaN
                95822       NaN       NaN       NaN       NaN       NaN
                95823       NaN       NaN       NaN       NaN       NaN
                95824       NaN       NaN       NaN       NaN       NaN
                95825       NaN       NaN       NaN       NaN       NaN
                95826       NaN       NaN       NaN       NaN       NaN
                95827       NaN       NaN       NaN       NaN       NaN
                95828       NaN       NaN       NaN  159900.0       NaN
                95829  598695.0       NaN       NaN       NaN       NaN
                95831       NaN       NaN       NaN       NaN       NaN
                95832       NaN       NaN       NaN       NaN       NaN
                95833       NaN       NaN       NaN       NaN       NaN
                95834       NaN       NaN       NaN       NaN       NaN
                95835       NaN       NaN       NaN       NaN       NaN
                95838       NaN       NaN       NaN       NaN       NaN
                95841       NaN       NaN       NaN       NaN       NaN
                95842       NaN       NaN       NaN       NaN       NaN
                95864       NaN       NaN       NaN       NaN       NaN
SHINGLE SPRINGS 95682       NaN       NaN       NaN       NaN       NaN
SLOUGHHOUSE     95683       NaN       NaN       NaN       NaN       NaN
WALNUT GROVE    95690       NaN       NaN       NaN       NaN       NaN
WEST SACRAMENTO 95691       NaN       NaN       NaN       NaN       NaN
WILTON          95693       NaN       NaN       NaN       NaN       NaN


beds                          8
baths                         4
city            zip
ANTELOPE        95843       NaN
AUBURN          95603       NaN
CAMERON PARK    95682       NaN
CARMICHAEL      95608       NaN
CITRUS HEIGHTS  95610       NaN
                95621       NaN
COOL            95614       NaN
DIAMOND SPRINGS 95619       NaN
EL DORADO       95623       NaN
EL DORADO HILLS 95762       NaN
ELK GROVE       95624       NaN
                95757       NaN
                95758       NaN
ELVERTA         95626       NaN
FAIR OAKS       95628       NaN
FOLSOM          95630       NaN
FORESTHILL      95631       NaN
GALT            95632       NaN
GARDEN VALLEY   95633       NaN
GOLD RIVER      95670       NaN
GRANITE BAY     95746       NaN
GREENWOOD       95635       NaN
LINCOLN         95648       NaN
LOOMIS          95650       NaN
MATHER          95655       NaN
MEADOW VISTA    95722       NaN
NORTH HIGHLANDS 95660       NaN
ORANGEVALE      95662       NaN
PENRYN          95663       NaN
PLACERVILLE     95667       NaN
...                         ...
SACRAMENTO      95814       NaN
                95815       NaN
                95816       NaN

In [39]:
pd.pivot_table(prices, index=['city'], values=['price'], columns=['beds'==2,'baths'==1], aggfunc=np.sum)

KeyError: 'city'